### ISSUE TITLE
全量微调或预训练13b需要什么硬件需求

### ISSUE THREAD

**Issue by thelongestusernameofall** [zjunlp/CaMA#10]
gpu显存多大，几个。
内存，
磁盘等需求。

感谢

**Comment by MikeDean2367** [comment]
您好，GPU显存方面，我们尝试过8张V100(32GB)上进行全量预训练(采用DeepSpeed ZeRO3)，速度可观。因此建议使用同等配置的显卡。

运行内存方面，来自两个开销，一个是由DeepSpeed ZeRO3策略产生的，另外一方面是数据加载产生的，如果使用我们的数据处理，则仅需要将索引文件加载到内存，数据加载产生的内存较小。在我们的3台8张V100设备上，单台机器700GB的内存，实际每台机器占用约100GB~200GB左右；若在单台8张V100设备上，实际每台机器占用约400~500GB。（以上的开销主要来自于DeepSpeed ZeRO3）

磁盘需求的话，我们实验的单台机器磁盘大小约在2TB左右。

以上只是我们的实验设备，仅供参考。
