### ISSUE TITLE
想问一下，hf上的模型是完成了预训练的模型还是原始模型？

### ISSUE THREAD

**Issue by twwch** [zjunlp/CaMA#11]
https://huggingface.co/zjunlp/CaMA-13B-Diff

https://huggingface.co/zjunlp/CaMA-13B-LoRA

这两个模型是已经完成了预训练的模型么？

**Comment by MikeDean2367** [comment]
您好。我们的训练包含了两个过程。

第一步是在我们构建的中英双语数据集上进行**全量二次预训练** ，预训练的权重与初始LLaMA-13B进行权重作差，作差后的权重上传到`https://huggingface.co/zjunlp/CaMA-13B-Diff`，您如果仅想要获得我们 **二次预训练后的结果** ，请按照[此处](https://github.com/zjunlp/CaMA#22-%E9%A2%84%E8%AE%AD%E7%BB%83%E6%A8%A1%E5%9E%8B%E6%9D%83%E9%87%8D%E8%8E%B7%E5%8F%96%E4%B8%8E%E6%81%A2%E5%A4%8D)的步骤进行即可得到。

我们的第二步是在第一步的基础上，使用我们构建的中英双语指令数据集，采用LoRA进行**指令微调** ，LoRA权重直接上传到`https://huggingface.co/zjunlp/CaMA-13B-LoRA`。该权重需要搭配第一步得到的结果（即二次预训练后的结果）进行使用。具体可以参考[此处](https://github.com/zjunlp/CaMA#2-%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B)。

**Comment by MikeDean2367** [comment]
您好，您执行的这个命令
```shell
python examples/generate_lora_web.py --base_model /data/nfs/CaMA-13B-Diff --lora_weights /data/models/CaMA-13B-LoRA
```
中的`/data/nfs/CaMA-13B-Diff`是直接从`https://huggingface.co/zjunlp/CaMA-13B-Diff`下载的吗？**如果是的话**，您需要参考[此处](https://github.com/zjunlp/CaMA#22-%E9%A2%84%E8%AE%AD%E7%BB%83%E6%A8%A1%E5%9E%8B%E6%9D%83%E9%87%8D%E8%8E%B7%E5%8F%96%E4%B8%8E%E6%81%A2%E5%A4%8D)的步骤，先将`LLaMA-13B`和`https://huggingface.co/zjunlp/CaMA-13B-Diff`进行合并，然后您将合并后的地址，传入到`--base_model`中。

**如果不是的话**，且您按照上面的步骤，进行合并了，仍出现错误，请告知我。

**Comment by twwch** [comment]
模型是https://huggingface.co/zjunlp/CaMA-13B-Diff下载的，我试试后面的步骤

**Comment by twwch** [comment]
已经正常了，多谢解答
