### ISSUE TITLE
预计什么时候会发布“全量指令微调版本“

### ISSUE THREAD

**Issue by xerrors** [zjunlp/CaMA#3]
注意到 README 中提到下一步的工作计划中包括：`训练并发布全量指令微调版本`，很是激动，所以想问一下大概什么会发布？一个月内？三个月内？或者晚些时候？

**Comment by zxlzr** [comment]
您好感谢关注，我们会尽快发布，受到GPU资源影响，目前无法确保全量微调的版本发布时间。

**Comment by xerrors** [comment]
好的，辛苦！！！
