### ISSUE TITLE
实体抽取数据集

### ISSUE THREAD

**Issue by Skypow2012** [zjunlp/CaMA#59]
你好，首先感谢你们分享的数据集~我们最近在做NLP领域的开源自动标注工具

然后我看了下 KnowLM-IE 数据集，里面好像都是 关系抽取相关的，我看项目截图里有关于“从给定的文本中提取出可能的实体和实体类型”的数据，是这部分 NER 的数据没有开源么？

**Comment by guihonghao** [comment]
你好，https://huggingface.co/datasets/zjunlp/knowlm-ke 这个数据集中包含 knowlm-13b-zhixi 训练中所使用的全部IE指令数据，包括NER、RE、EE等任务。
