### ISSUE TITLE
如果要把LoRA权重也合并进去，怎么操作？

### ISSUE THREAD

**Issue by apachemycat** [zjunlp/CaMA#6]
说明中只有合并原模型与Dif的，如果继续合并Lora模型怎么做？
合并Lora模型后，还能在此基础上继续Fine tuning或者Instrct tuning吗？

**Comment by MikeDean2367** [comment]
您好，是可以继续合并的，代码可以参考[此处](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E6%89%8B%E5%8A%A8%E6%A8%A1%E5%9E%8B%E5%90%88%E5%B9%B6%E4%B8%8E%E8%BD%AC%E6%8D%A2#step-2-%E5%90%88%E5%B9%B6lora%E6%9D%83%E9%87%8D%E7%94%9F%E6%88%90%E5%85%A8%E9%87%8F%E6%A8%A1%E5%9E%8B%E6%9D%83%E9%87%8D)。在合并完成后，您会得到一个完整的权重，从代码的可行性上来说是可以继续fine-tune或者instruct tune的。

**Comment by apachemycat** [comment]
多谢，我看了您提供的参考，我有个疑问
多LoRA权重合并也是支持的，意味着Base模型上分别用两套数据集训练出来两套LoRA 权重是可以了，这样吧两个权重合并到Base上，与先合并一个权重，然后在这个合并的结果上继续训练，然后再把训练好的权重合并到之前合并的结果里，这两种有什么区别？

**Comment by MikeDean2367** [comment]
您好，我没有理解您的意思。我们的模型训练分为两个阶段，第一个阶段是使用中英语料进行全量二次预训练，没有使用LoRA；第二个阶段是用第一步的模型，使用我们构建的指令数据集，使用LoRA微调。

您的问题中提到了`多LoRA`，在我们的实验中没有这个情况。如果您指的是`Chinese LLaMA`仓库的话，建议您去咨询他们。（我的理解是他那边的同时合并，并不意味着同时训练，而是使用的您提到的第二种训练，假设base是A，我在A基础上训练了LoRA  B，在A+B的基础上训练了LoRA C，那么最后有3个权重，分别是A,B,C，合并的时候可以是先合并（A+B）+C，也可以是A+(B+C)，因此您从合并的顺序来推导出训练的顺序是不唯一的）。

最后从技术层面讨论一下这两个的区别。首先对于第一个情况，是一种并行合并，我的理解是`分别训练，即用预训练语料在原版LLaMA上用LoRA训练，得到一个权重，用指令语料在原版LLaMA上再次用LoRA训练得到一个权重，最后再将两个LoRA进行合并`，这个训练做法没有问题，但是这两个训练过程本来就是独立无关的，因此这种合并是不合理的，在我的知识范围内，这个做法不存在理论支持。对于第二个情况才是正确的且合理的。
