### ISSUE TITLE
合并Llama与DIFF的代码是否有问题？

### ISSUE THREAD

**Issue by apachemycat** [zjunlp/CaMA#7]
tokenizer_raw: transformers.LlamaTokenizer = transformers.LlamaTokenizer.from_pretrained(**path_diff**)
    model_raw: transformers.PreTrainedModel = transformers.AutoModelForCausalLM.from_pretrained(
        **path_raw**,
        device_map={"": torch.device(device)},
        torch_dtype=torch.float32,
        low_cpu_mem_usage=True,
    )
代码中 tokenizer_row与 model_raw对应的不是同一个模型，是否都应该对应**path_raw**

**Comment by MikeDean2367** [comment]
您好，我们在huggingface的diff仓库上传的tokenizer就是由huggingface转换的的tokenizer（即由2.2小节转换步骤2得到的tokenizer），且在model_diff的recover中，tokenizer仅仅是加载和保存，并没有其他变化，因此不管是path_diff还是path_raw，加载的tokenizer是同一个。

**Comment by apachemycat** [comment]
多谢提醒，
